# Book settings
title: Demos for UCLAx Webinar Intro to Data Science
author: Benjamin J. Winjum
copyright: '2021'

# Launch button settings
repository:
  url: https://github.com/benjum/uclax-intro-data-science
  path_to_book: book
  branch: main

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: true

